### ISSUE TITLE
Index page gives 500 Internal Server Error

### ISSUE THREAD

**Issue by gondaruk** [timercrack/pydatacoll#24]
```python
Traceback (most recent call last):
  File "/Users/nazar/.virtualenvs/datacoll/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/Users/nazar/.virtualenvs/datacoll/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/Users/nazar/.virtualenvs/datacoll/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 161, in handler_wrapper
    result = await result
  File "/Users/nazar/Work/Devel/datacoll/pydatacoll/api_server.py", line 119, in get_index
    route._path))
AttributeError: 'ResourceRoute' object has no attribute '_path'
```

**Comment by pualt164i** [comment]
I got the same errors, any help?
